image: alpine/edge
packages:
  - pandoc
  - curl
  - jq
secrets:
  - 5daebabf-5eed-4d09-9ded-61aee555be44
environment:
  REPO_ID: 218443
  README: README.html
tasks:
  - convert-readme: |
      pandoc -o README.html ./keyoxidizer/readme.org
  - update-readme: |
      set +x  # Avoid echoing the token
      jq -sR '{
          "query": "mutation UpdateRepo($id: Int!, $readme: String!) {
                       updateRepository(id: $id, input: { readme: $readme }) { id }
                   }",
          "variables": {
            "id": '$REPO_ID',
            "readme": .
          } }' < $README \
        | curl --oauth2-bearer "$(cat ~/.api-token)" \
          -H "Content-Type: application/json" \
          -d@- https://git.sr.ht/query &&
      echo "README set"
