#+TITLE:Keyoxidizer - Interactive Keyoxide helper

* Objective
This is a simple utility designed to make working with [[https://keyoxide.org][Keyoxide]] easier. Keyoxidizer guides the user with prompts to gather their (name, email, etc.) and then handles all the details to generate the PGP key and exports it to [[https://keys.openpgp.org][OpenPGP]] key server. It will then guide the user in proving ownership their online accounts supported by Keyoxide.
This is an unofficial thin wrapper around Keyoxide but it does not (and may never) support all Keyoxide features.

* Usage
** Option 1
Clone the repo. Run the script.
#+BEGIN_SRC sh
git clone git@github.com:shombando/keyoxidizer.git
cd keyoxidizer
./keyoxidizer.sh
#+END_SRC

** Option 2
Download the ~keyoxidizer.sh~ script and put it in a keyoxidizer folder (recommended) and open a terminal window in that location, change the file permission to make it executable and then run it:
#+BEGIN_SRC sh
chmod +x ./keyoxidizer.sh
./keyoxidizer.sh
#+END_SRC

* Supported Platforms
- Domain/DNS (note: sometimes DNS records take some time to update)
- Gitea
- Github
- Mastodon

* Roadmap
First support loading an existing key that was created by the tool so I can incrementally add support for adding proofs to the [[https://keyoxide.org/guides][the different platforms]]. They will be listed under the [[Supported Platforms]] sections.

* Contributing
I absolutely welcome feedback in the form of PRs, whether it is improving my shell scripting or adding new functionality. A few guidelines to help me out:
- each PR should be focused on a single aspect (add functionality / improve existing functionality)
- draft PRs are encouraged so we can collaborate better
- if you're refactoring please explain the changes so I can learn from it
