#+TITLE: Keyoxidizer - Interactive Keyoxide helper

* Objective
This is a simple utility designed to make working with [[getting][Keyoxide]]. Keyoxidizer presents the user with prompts to collect the user specific information and then generates the PGP key and exports it to [[https://keys.openpgp.org][OpenPGP]] key server. This is an unofficial thin wrapper around Keyoxide to make it easier for folks who want to verify their identity but might find the process steps cumbersome without the prompts.

* Supported Platforms
- Mastodon (adding notation requires user copy-paste looking for better solution)

* Roadmap
First support loading an existing key that was created by the tool so I can incrementally add support for adding proofs to the [[https://keyoxide.org/guides][the different platforms]]. They will be listed under the [[Supported Platforms]] sections.

* Contributing
I absolutely welcome feedback in the form of PRs, whether it is improving my shell scripting or adding new functionality. A few guidelines to help me out:
- each PR should be focused on a single aspect (add functionality / improve existing functionality)
- draft PRs are encouraged so we can collaborate better
- if you're refactoring please explain the changes so I can learn from it
